amazon_crawler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
import debug_toolbar
from django.contrib.auth.views import (
    password_reset_done,
    password_reset_confirm,
    password_reset_complete)


urlpatterns = [
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^guwei_administration/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^find_none/', views.find_none, name='find_none'),
    url(r'^converter/', views.converter, name='converter'),
    url(r'^keyword_rank/', include('keyword_rank.urls', namespace='keyword_rank')),
    url(r'^rele_keyword/', include('rele_keyword.urls', namespace='rele_keyword')),
    url(r'^inventory/', include('inventory.urls', namespace='inventory')),
    url(r'^asin_keyword/', include('asin_keyword.urls', namespace='asin_keyword')),
    url(r'^asin_detail/', include('asin_detail.urls', namespace='asin_detail')),
    url(r'^follow_sale/', include('follow_sale.urls', namespace='follow_sale')),
    url(r'^prime_asins/', include('prime_asins.urls', namespace='prime_asins')),
    url(r'^review_monitor/', include('review_monitor.urls', namespace='review_monitor')),
    url(r'^review_qa_collect/', include('review_qa_collect.urls', namespace='review_qa_collect')),
    url(r'^short_url/', include('short_url.urls', namespace='short_url')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^actions/', include('actions.urls', namespace='actions')),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^recharge/', include('payment.urls', namespace='payment')),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^core/', include('core.urls', namespace='core')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^(?P<shorten_id>\w{6})$',views.redirect_original, name='redirectoriginal'),
    url(r'^password/reset/done/$',password_reset_done,name='password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^password_reset_complete/$',password_reset_complete,name='password_reset_complete'),
    url(r'^check/', views.check, name='check'),
    # when short URL is requested it redirects to original URL
]

blog/urls.py
from django.conf.urls import url

from .views import BlogDetailView, BlogListView, BlogTagListView


urlpatterns = [
    url(r'^$',BlogListView.as_view(),name='blog_list_view'),
    url(r'^tag/(?P<tag>[\w ]+)/$',BlogTagListView.as_view(),name='blog_tag_list_view'),
    url(r'^(?P<slug>[\w-]+)/$',BlogDetailView.as_view(),name='blog_detail_view'),
]

payment/urls.py
#-*- coding:utf-8 -*-

from django.views.generic import TemplateView
from . import views
from django.conf.urls import url


urlpatterns =[
    url(r'^$', TemplateView.as_view(template_name="crawler/payment/recharge.html"), name='recharge'),
    url(r'^success/$', TemplateView.as_view(template_name="crawler/payment/success.html"), name="payment_success"),
    url(r'^error/$', TemplateView.as_view(template_name="crawler/payment/error.html"), name="payment_error"),
    url(r'^upgrade/(?P<add_credit>\w+)/$', views.upgrade_account, name="upgrade_account"),
    url(r'^return_url/$', views.return_url_handler, name="payment_return_url"),
    url(r'^notify_url/$', views.notify_url_handler, name="payment_notify_url"),
]

rele_keyword/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.in_word, name='in_word'),
]

rele_keyword/models.py
from django.db import models


class In_word(models.Model):
    COUNTRY_CHOICES = (('us', '美国'),('ca', '加拿大'),('fr', '法国'),
                       ('de', '德国'),('it', '意大利'),('jp', '日本'),
                       ('es', '西班牙'),('uk', '英国'),)
    in_word = models.CharField(max_length = 1000)
    country = models.CharField(max_length=50,choices=COUNTRY_CHOICES,default='us')


class Out_word(models.Model):
    in_out = models.ForeignKey(In_word,related_name='out_word')
    out_word = models.CharField(max_length = 1000)

rele_keyword/forms.py
from django import forms
from .models import In_word


class In_word_Form(forms.ModelForm):

    class Meta:
        model = In_word
        fields = ('in_word','country',)

rele_keyword/views.py
from django.shortcuts import render
from .forms import In_word_Form
from .rele_keyword import get_rele_word
from celery import group
import itertools


def in_word(request):
    out_words=None
    form = In_word_Form(data=request.POST or None)
    if form.is_valid():
        new_word=form.save(commit=False)
        second_word=get_rele_word.s(new_word.in_word,new_word.country)
        third_words=group(get_rele_word.s(i,new_word.country) for i in second_word())()
        out_words = []
        for i in third_words:
            try:
                out_words+=i.get()
            except:
                pass
    return render(request, 'crawler/rele_keyword/in_word.html', {'form':form, 'out_words': out_words})

rele_keyword/templates/crawler/rele_keyword/in_word.html
{% extends 'base.html' %}
{% block title %} 相关关键词查询 | {{ site_name }}{% endblock %}
{% load static %}
<!-- Add custom CSS here -->
 {% block customcss %}
 <style>
 #container {
  margin: 0 auto;
  width: 100px;
  height: 100px;
  margin-left: calc(50% - 100px);
  position: relative;
  }
 ._hide{
  display:none;
}

  td{padding:8px;line-height:1.42857143;vertical-align:top;border-top:1px solid #ddd;}

</style>
{% endblock %}

{% block rootcontainer %}
    <div class="search_description">
     {% if user.is_authenticated %}
        <span>当前剩余积分：<i class="red">{{user.settings.credit}}</i></span>
        <span class="buy">积分不够？<a href="{% url 'payment:recharge' %}" target="_blank">立即购买</a></span>
    {% else %}
    <span>新用户免费获得100积分,免费查询竞品信息,每跟踪一个月消耗<i class="red">&nbsp;6&nbsp;</i>积分</span>
    {% endif %}
	 <span class="buy"><a href="/blog/xiangguan/"><i class="fa fa-lightbulb-o" aria-hidden="true"></i>&nbsp;使用说明</a></span>

    </div>

<div class="container">
    <div id="content">
        {% if messages %} <!--messages的用法-->
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }} <!--safe的用法-->
                        <a href="#" class="close">×</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
<div class="row">
        <div class="col-lg-12 ">
            <div class="search_box">
                <form action="." method="post" id="login_form">
                    <input id="id_in_word" class="search_input" placeholder="请输入KeyWords" maxlength="100" name="in_word" type="text" required="">
                    <select  class="search_select" id="id_country" name="country" required="">
                    <option value="us" selected="selected">美国</option>
                    <option value="ca">加拿大</option>
                    <option value="jp">日本</option>
                    <option value="fr">法国</option>
                    <option value="uk">英国</option>
                    <option value="de">德国</option>
                    <option value="it">意大利</option>
                    <option value="es">西班牙</option>
                </select>
	            {% csrf_token %}
                <input type="submit" style="width:196px" value="获得相关关键词" onclick="get(),start()">
            </form>
            </div>
        </div>

        <div class="col-lg-12 ">
        <img src="{% static "images/spin.gif" %}" id="gif" style="display: none; margin: 0 auto; width: 100px; /* visibility: hidden; */">
        </div>
</div>

    <div class="row-sm-12 col-sm-offset-1">
	     <div id="container"></div>
        {% if out_words %}
                <ul class="messages"><li class="success">相关关键词</li></ul>
                <div style="overflow: auto;text-align: center; margin:20px" id="result" >
                 <table width="98%" style="border: outset;">
            {% for out_word in out_words %}
                   <tr><td>{{ out_word }}</td></tr>
            {% empty %}
            {% endfor %}
            </table>
                </div>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block extrajsexternal %}
<script src="{% static 'progressbar/progressbar.min.js' %}"></script>
<script>
    $("#container").hide();
    function start(){
      $("#container").hide();
      $("#result").html("");
      if($("#id_in_word").val().trim() === ""){
        return;
      }
      var bar = new ProgressBar.Circle(container, {
      color: '#aaa',
      // This has to be the same size as the maximum width to
      // prevent clipping
      strokeWidth: 4,
      trailWidth: 1,
      easing: 'easeInOut',
      duration: 35000,
      text: {
        autoStyleContainer: false
      },
      from: { color: '#aaa', width: 1 },
      to: { color: '#333', width: 4 },
      // Set default step function for all animate calls
      step: function(state, circle) {
        circle.path.setAttribute('stroke', state.color);
        circle.path.setAttribute('stroke-width', state.width);

        var value = Math.round(circle.value() * 100);
        if (value === 0) {
          circle.setText('');
        } else {
          $("#container").show();
          circle.setText(value + ' %');
        }
      }
    });
    bar.text.style.fontFamily = '"Microsoft YaHei", Helvetica, sans-serif';
    bar.text.style.fontSize = '2rem';
    bar.animate(1.0);
  }
</script>


{% endblock %}