amazon_crawler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
import debug_toolbar
from django.contrib.auth.views import (
    password_reset_done,
    password_reset_confirm,
    password_reset_complete)


urlpatterns = [
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^guwei_administration/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^find_none/', views.find_none, name='find_none'),
    url(r'^converter/', views.converter, name='converter'),
    url(r'^keyword_rank/', include('keyword_rank.urls', namespace='keyword_rank')),
    url(r'^rele_keyword/', include('rele_keyword.urls', namespace='rele_keyword')),
    url(r'^inventory/', include('inventory.urls', namespace='inventory')),
    url(r'^asin_keyword/', include('asin_keyword.urls', namespace='asin_keyword')),
    url(r'^asin_detail/', include('asin_detail.urls', namespace='asin_detail')),
    url(r'^follow_sale/', include('follow_sale.urls', namespace='follow_sale')),
    url(r'^prime_asins/', include('prime_asins.urls', namespace='prime_asins')),
    url(r'^review_monitor/', include('review_monitor.urls', namespace='review_monitor')),
    url(r'^review_qa_collect/', include('review_qa_collect.urls', namespace='review_qa_collect')),
    url(r'^short_url/', include('short_url.urls', namespace='short_url')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^actions/', include('actions.urls', namespace='actions')),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^recharge/', include('payment.urls', namespace='payment')),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^core/', include('core.urls', namespace='core')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^(?P<shorten_id>\w{6})$',views.redirect_original, name='redirectoriginal'),
    url(r'^password/reset/done/$',password_reset_done,name='password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^password_reset_complete/$',password_reset_complete,name='password_reset_complete'),
    url(r'^check/', views.check, name='check'),
    # when short URL is requested it redirects to original URL
]

blog/urls.py
from django.conf.urls import url

from .views import BlogDetailView, BlogListView, BlogTagListView


urlpatterns = [
    url(r'^$',BlogListView.as_view(),name='blog_list_view'),
    url(r'^tag/(?P<tag>[\w ]+)/$',BlogTagListView.as_view(),name='blog_tag_list_view'),
    url(r'^(?P<slug>[\w-]+)/$',BlogDetailView.as_view(),name='blog_detail_view'),
]

prime_asins/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.asin_submit, name='asin_submit'),
    url(r'^(?P<country>[-\w]+)/$', views.asin_submit, name='asin_submit_country'),
    url(r'^(?P<country>[-\w]+)/(?P<category>[-\w\s/&]+)/$',
           views.asin_submit,
           name='asin_submit_category'),
]

prime_asins/models.py
from django.db import models


class Asin_detail(models.Model):
    sell_rank = models.IntegerField(verbose_name=u"销售额排行", blank=True, null=True)
    sell_quant = models.IntegerField(verbose_name=u"销售数量", blank=True, null=True)
    sell_amount = models.IntegerField(verbose_name=u"销售额", blank=True, null=True)
    fu_sell_quant = models.IntegerField(verbose_name=u"父体销售数量", blank=True, null=True)
    fu_sell_amout = models.IntegerField(verbose_name=u"父体销售额", blank=True, null=True)

    COUNTRY_CHOICES = (('us', '美国'),('ca', '加拿大'),('fr', '法国'),
                       ('de', '德国'),('it', '意大利'),('jp', '日本'),
                       ('es', '西班牙'),('uk', '英国'),)

    country = models.CharField(verbose_name=u'国别', choices=COUNTRY_CHOICES, max_length=60, default="us")

    img_url= models.URLField(null=True,verbose_name=u"图片", max_length=5000)
    detail_page_url = models.URLField(null=True,verbose_name=u"网页", max_length=5000)
    price = models.CharField(max_length=50,verbose_name=u"价格", null = True)
    brand = models.CharField(max_length=500,verbose_name=u"品牌", null = True)
    label = models.CharField(max_length=500,verbose_name=u"标牌", null = True)
    bsr_rank = models.PositiveIntegerField(null=True,verbose_name=u"排名", blank=True)
    description = models.CharField(max_length=1000, verbose_name=u"描述", blank=False, null=True)
    asin = models.CharField(max_length=200, verbose_name=u"ASIN", blank=True, null=True)
    title = models.CharField(max_length=1000, verbose_name=u"标题", blank=True, null=True)
    fu_asin = models.CharField(max_length=200, verbose_name=u"父体ASIN", blank=True, null=True)
    fu_asin_title = models.CharField(max_length=1000, verbose_name=u"父体ASIN标题", blank=True, null=True)
    created = models.DateTimeField(blank = True,null = True,auto_now_add=True)

    class Meta:
        ordering = ['description','sell_rank']

    def __str__(self):
        return '%s的商品 %s 的详情' % (self.get_country_display(), self.asin)


class ImportFile(models.Model):

    file = models.FileField(upload_to='static/documents/')
    name = models.CharField(max_length=500, verbose_name=u'文件名')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

prime_asins/views.py
from django.shortcuts import render, redirect
from prime_asins.models import Asin_detail
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
#from accounts.models import UserSettings
#from core.amazon_api import ABOVE_V1
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def asin_submit(request, country='us', category=None):
    #if not UserSettings.objects.get(user=request.user).status in ABOVE_V1:
    #    messages.success(request, '请购买VIP后继续使用网站功能.')
    #    return redirect('/recharge')
    asin_details = Asin_detail.objects.filter(country=country)
    asin_details = asin_details.order_by('description','sell_rank')

    countries = [country[0] for country in Asin_detail.COUNTRY_CHOICES]
    categories = [category[0] for category in Asin_detail.objects.filter(country=country).values_list('description').distinct('description')]

    if category:
        #asin_details = asin_details.filter(description__startswith=category)
        asin_details = asin_details.filter(description=category)

    paginator = Paginator(asin_details, 200)
    page = request.GET.get('page')
    try:
        asin_detail_page = paginator.page(page)
    except PageNotAnInteger:
        asin_detail_page = paginator.page(1)
    except EmptyPage:
        asin_detail_page = paginator.page(paginator.num_pages)

    return render(request, 'crawler/prime_asins/asin_submit.html', {'country':country,'countries':countries,'categories':categories,'category':category,'asin_details': asin_detail_page,})

prime_asins/templates/crawler/prime_asins/asin_submit.html
{% extends 'base.html' %}

{% load static %}
{% block title %}PRIME DAY热销商品详情 | {{ site_name }}{% endblock %}
{% block extracss %}
{% endblock %}
{% block rootcontainer %}
<div class="container">

<div class="row">
    <div class="col-lg-12">
        <ul>
            {% for coun in countries %}
            <li {% ifequal coun country %}class="selected"{% endifequal %}><a href="{% url 'prime_asins:asin_submit_country' coun %}">{{ coun }}</a></li>
            {% endfor %}
        </ul>
        <ul>
            {% for cate in categories %}
            <li {% ifequal cate category %}class="selected"{% endifequal %}><a href="{% url 'prime_asins:asin_submit_category' country=country category=cate %}">{{ cate }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <br>
        <div style="overflow: auto;">
            <table id="change" class="display" cellspacing="0" width="98%">
                <thead>
                    <tr>
                        <th width="6%">类别</th>
                        <th width="6%">类别下排名</th>
                        <th width="28%">图片</th>
                        <th width="28%">销售数量</th>
                        <th width="8%">销售额</th>
                        <th width="8%">ASIN</th>
                        <th width="18%">商品名称</th>
                        <th width="6%">价格</th>
                        <th width="6%">BSR</th>
                        <th width="10%">商标</th>
                    </tr>
                </thead>
                <tbody>
                {% if asin_details %}{% include "crawler/action/pagination.html" with page=asin_details %}{% endif %}
                {% for asin_detail in asin_details %}
                    <tr id="item">
                        <td>{{ asin_detail.description }} </td>
                        <td>{{ asin_detail.sell_rank }} </td>
                        <td><img src="{% if asin_detail.img_url %}{{ asin_detail.img_url }} {% endif %}"></td>
                        <td>{{ asin_detail.fu_sell_quant }} </td>
                        <td>{{ asin_detail.fu_sell_amout }}</td>
                        <td> <a href="{{asin_detail.detail_page_url}}" target="_blank">{{ asin_detail.fu_asin }} </a> </td>
                        <td>{{ asin_detail.fu_asin_title }} </td>
                        <td>{{ asin_detail.price }}</td>
                        <td>{{ asin_detail.bsr_rank }}</td>
                        <td>{{ asin_detail.brand }} ({{ asin_detail.label }})</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
</div>
</div>
{% endblock %}