amazon_crawler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
import debug_toolbar
from django.contrib.auth.views import (
    password_reset_done,
    password_reset_confirm,
    password_reset_complete)


urlpatterns = [
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^guwei_administration/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^find_none/', views.find_none, name='find_none'),
    url(r'^converter/', views.converter, name='converter'),
    url(r'^keyword_rank/', include('keyword_rank.urls', namespace='keyword_rank')),
    url(r'^rele_keyword/', include('rele_keyword.urls', namespace='rele_keyword')),
    url(r'^inventory/', include('inventory.urls', namespace='inventory')),
    url(r'^asin_keyword/', include('asin_keyword.urls', namespace='asin_keyword')),
    url(r'^asin_detail/', include('asin_detail.urls', namespace='asin_detail')),
    url(r'^follow_sale/', include('follow_sale.urls', namespace='follow_sale')),
    url(r'^prime_asins/', include('prime_asins.urls', namespace='prime_asins')),
    url(r'^review_monitor/', include('review_monitor.urls', namespace='review_monitor')),
    url(r'^review_qa_collect/', include('review_qa_collect.urls', namespace='review_qa_collect')),
    url(r'^short_url/', include('short_url.urls', namespace='short_url')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^actions/', include('actions.urls', namespace='actions')),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^recharge/', include('payment.urls', namespace='payment')),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^core/', include('core.urls', namespace='core')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^(?P<shorten_id>\w{6})$',views.redirect_original, name='redirectoriginal'),
    url(r'^password/reset/done/$',password_reset_done,name='password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^password_reset_complete/$',password_reset_complete,name='password_reset_complete'),
    url(r'^check/', views.check, name='check'),
    # when short URL is requested it redirects to original URL
]

asin_detail/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.asin_submit, name='asin_submit'),
]

blog/urls.py
from django.conf.urls import url

from .views import BlogDetailView, BlogListView, BlogTagListView


urlpatterns = [
    url(r'^$',BlogListView.as_view(),name='blog_list_view'),
    url(r'^tag/(?P<tag>[\w ]+)/$',BlogTagListView.as_view(),name='blog_tag_list_view'),
    url(r'^(?P<slug>[\w-]+)/$',BlogDetailView.as_view(),name='blog_detail_view'),
]

core/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.core.urlresolvers import reverse
from django.utils.text import slugify
import random
from django.conf import settings


class TimeStampedModel(models.Model):
    """
    Abstract base class that provides self-updating 'created' and 'modified'
    fields.
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(models.Model):
    content = RichTextField()


class Product(models.Model):
    COUNTRY_CHOICES = (('us', '美国'),('ca', '加拿大'),('fr', '法国'),
                       ('de', '德国'),('it', '意大利'),('jp', '日本'),
                       ('es', '西班牙'),('uk', '英国'),)
    asin = models.CharField(max_length = 400)
    asins_in = models.TextField()
    title = models.CharField(max_length = 5000)
    created = models.DateTimeField(blank = True,null = True,auto_now_add=True)
    brand = models.CharField(max_length=500,null = True)
    country = models.CharField(max_length=50,choices=COUNTRY_CHOICES,default='us')
    img_url= models.URLField(null=True,max_length=5000)
    detail_page_url = models.URLField(null=True,max_length=5000)
    price = models.CharField(max_length=50,null = True)
    re_qa_slug=models.SlugField(max_length=250,null=True,blank=False,editable=True,unique=True)
    updated = models.DateTimeField(auto_now=True)
    label = models.CharField(max_length=500,null = True)
    bsr_rank = models.PositiveIntegerField(null=True,blank=True)
    text = models.CharField(max_length=2000)
    review_qa = models.BooleanField(default=False)
    detail = models.BooleanField(default=False)
    review_qa_apply_time = models.DateTimeField(null=True)
    review_qa_complete_time = models.DateTimeField(null=True)
    #user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='product_review_qa_to_user',blank=True)
    #user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='asin_detail',blank=True)

    def __str__(self):
        if self.review_qa:
            return '%s 的 %s 的问答和评论' % (self.get_country_display(), self.asin)
        else:
            return '%s的商品 %s 的详情' % (self.get_country_display(), self.asin)

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        if self.review_qa:
            return reverse('review_qa_collect:product_detail', args=[self.re_qa_slug])

    def save(self, *args, **kwargs):
        if self.review_qa and not self.re_qa_slug:
            self.re_qa_slug = slugify(self.asin+str(random.randrange(1000)))
        if not self.text:
            if self.review_qa:
                self.text = '%s的商品 %s 的问答和评论' % (self.get_country_display(), self.asin)
            else:
                self.text = '%s的商品 %s 的详情' % (self.get_country_display(), self.asin)
        super(Product, self).save(*args, **kwargs)


class Product_to_user(models.Model):
    asin = models.ForeignKey(Product,related_name='Product_to_User')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='Product_to_User',blank=True)
    created = models.DateTimeField(auto_now_add=True,db_index=True)
    updated = models.DateTimeField(auto_now=True)
    review_qa = models.BooleanField(default=False)
    detail = models.BooleanField(default=False)

asin_detail/forms.py
from django import forms
from core.models import Product


class Asin_detail_Form(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('country','asins_in',)

asin_detail/views.py
from django.shortcuts import render, redirect
from .forms import Asin_detail_Form
from core.models import Product,Product_to_user
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from accounts.models import UserSettings
from core.amazon_api import ABOVE_V1
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def asin_submit(request):
#    if not UserSettings.objects.get(user=request.user).status in ABOVE_V1:
#        messages.success(request, '请购买VIP后继续使用网站功能.')
#        return redirect('/recharge')

    detail_to_user = Product_to_user.objects.filter(user=request.user,detail=True)
    asin_details = detail_to_user.values_list('asin', flat=True)
    asin_details = Product.objects.filter(id__in=asin_details)

    form = Asin_detail_Form()
    if 'asins_in' in request.POST:
        form = Asin_detail_Form(data=request.POST or None)
        print(request.POST,form.is_valid())
        if form.is_valid():
            new_asin = form.save(commit=False)
            for asin in new_asin.asins_in.splitlines():
                if not Product.objects.filter(asin=asin,country=new_asin.country,detail=True):
                    if Product.objects.filter(asin=asin,country=new_asin.country):
                        product=Product.objects.filter(asin=asin,country=new_asin.country)[0]
                        product.detail=True
                        product.save()
                    else:
                        product=Product(asin=asin,country=new_asin.country,detail=True)
                        product.save()
                    if not Product_to_user.objects.filter(asin=product,user=request.user,detail=True):
                        detail_to_user=Product_to_user(asin=product,user=request.user,detail=True)
                        detail_to_user.save()
                else:
                    product=Product.objects.get(asin=asin,country=new_asin.country,detail=True)
                    if not Product_to_user.objects.filter(asin=product,user=request.user,detail=True):
                        if Product_to_user.objects.filter(asin=product,user=request.user):
                            detail_to_user=Product_to_user.objects.get(asin=product,user=request.user)
                            detail_to_user.detail=True
                            detail_to_user.save()
                        else:
                            detail_to_user=Product_to_user(asin=product,user=request.user,detail=True)
                            detail_to_user.save()

            messages.success(request, '查询任务已经保存,稍后开始为您查询.')
            return redirect('/asin_detail/')
    elif 'delete' in request.POST:
        products=Product.objects.filter(pk__in=request.POST.getlist('delete'))
        Product_to_user.objects.filter(asin__in=products,user=request.user).prefetch_related().update(detail=False)
        return redirect('/asin_detail/')

    paginator = Paginator(asin_details, 200)
    page = request.GET.get('page')
    try:
        asin_detail_page = paginator.page(page)
    except PageNotAnInteger:
        asin_detail_page = paginator.page(1)
    except EmptyPage:
        asin_detail_page = paginator.page(paginator.num_pages)

    return render(request, 'crawler/asin_detail/asin_submit.html', {'form':form,'asin_details': asin_detail_page,})

asin_detail/templates/crawler/asin_detail/asin_submit.html
{% extends 'base.html' %}
{% load asin_detail_tags %}

{% load static %}
{% block title %}批量从商品ASIN获得详情 | {{ site_name }}{% endblock %}
{% block extracss %}
{% endblock %}
{% block rootcontainer %}
<div class="container">
    {% if messages %}
     <ul class="messages">
       {% for message in messages %}
         <li class="{{ message.tags }}">
            {{ message|safe }}
            <a href="#" class="close">✖</a>
         </li>
       {% endfor %}
     </ul>
   {% endif %}

<div class="row">
    <div class="col-lg-12">
        <br>
        <form action="." method="post" onsubmit="showLoading();" id="login_form">
                {{ form.as_p }}
                {% csrf_token %}
            <input type="submit" class="btn btn-success" value="从ASIN获得商品详情" onclick="get();">
        </form>
    </div>

    <div class="col-lg-12 ">
        <img src="{% static "images/spin.gif" %}" id="gif" style="display: none; margin: 0 auto; width: 100px; /*visibility: hidden;*/">
    </div>
    <br>
    {% if asin_details %}
    {% latest_inven request.user.id as number %}
        结果的数目:{{ number }}
    <form method="post" id="changelist-form">
        {% csrf_token %}
        <button type="submit" class="button" title="Run the selected action" name="index" value="0">批量删除</button>
        <div style="overflow: auto;">
            <table id="change" class="display" cellspacing="0" width="98%">
                <thead>
                    <tr>
                        <th width="3%">操作</th>
                        <th width="6%">国家</th>
                        <th width="28%">图片</th>
                        <th width="8%">ASIN</th>
                        <th width="18%">商品名称</th>
                        <th width="6%">价格</th>
                        <th width="6%">BSR</th>
                        <th width="10%">商标</th>
                    </tr>
                </thead>
                <tbody>
                {% if asin_details %}{% include "crawler/action/pagination.html" with page=asin_details %}{% endif %}
                {% for asin_detail in asin_details %}
                    <tr id="item">
                        <td><input type="checkbox" name="delete" value="{{ asin_detail.pk }}"></td>
                        <td>{{ asin_detail.get_country_display }} </td>
                        <td><img src="{% if asin_detail.img_url %}{{ asin_detail.img_url }} {% endif %}"></td>
                        <td > <a href="{{asin_detail.detail_page_url}}" target="_blank">{{ asin_detail.asin }} </a> </td>
                        <td>{{ asin_detail.title }} </td>
                        <td>{{ asin_detail.price }}</td>
                        <td>{{ asin_detail.bsr_rank }}</td>
                        <td>{{ asin_detail.brand }} ({{ asin_detail.label }})</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </form>
    {% endif %}
</div>
</div>
{% endblock %}

asin_detail/templates/crawler/asin_detail/asin_submit_backup.html
{% extends 'base.html' %}
{% load asin_detail_tags %}

{% load static %}
{% block title %}批量从商品ASIN获得详情 | {{ site_name }}{% endblock %}
{% block extracss %}
{% endblock %}
{% block rootcontainer %}
<div class="container">
    {% if messages %}
     <ul class="messages">
       {% for message in messages %}
         <li class="{{ message.tags }}">
            {{ message|safe }}
            <a href="#" class="close">✖</a>
         </li>
       {% endfor %}
     </ul>
   {% endif %}

<div class="row">
    <div class="col-lg-12">
        <br>
        <form action="." method="post" onsubmit="showLoading();" id="login_form">
            <div>
                {{ form.as_p }}
                {% csrf_token %}
            <input type="submit"  class="btn btn-success" value="从ASIN获得商品详情" onclick="get();">
            </div>
        </form>
    </div>

    <div class="col-lg-12 ">
        <img src="{% static "images/spin.gif" %}" id="gif" style="display: none; margin: 0 auto; width: 100px; /*visibility: hidden;*/">
    </div>
    <br>
    {% if asin_details %}
    {% latest_inven request.user.id as number %}
        结果的数目:{{ number }}
        <div style="overflow: auto;">
            <table id="change" class="display" cellspacing="0" width="98%">
                <thead>
                    <tr>
                        <th width="6%">国家</th>
                        <th width="28%">图片</th>
                        <th width="8%">ASIN</th>
                        <th width="18%">商品名称</th>
                        <th width="6%">价格</th>
                        <th width="6%">BSR</th>
                        <th width="10%">商标</th>
                        <th width="8%">操作</th>
                    </tr>
                </thead>
                <tbody>
                {% for asin_detail in asin_details %}
                    <tr id="item">
                        <td>{{ asin_detail.get_country_display }} </td>
                        <td><img src="{% if asin_detail.img_url %}{{ asin_detail.img_url }} {% endif %}"></td>
                        <td > <a href="{{asin_detail.detail_page_url}}" target="_blank">{{ asin_detail.asin }} </a> </td>
                        <td>{{ asin_detail.title }} </td>
                        <td>{{ asin_detail.price }}</td>
                        <td>{{ asin_detail.bsr_rank }}</td>
                        <td>{{ asin_detail.brand }} ({{ asin_detail.label }})</td>
                        <td><a id='delete-item-{{asin_detail.id}}' href="/asin_detail/delete/{{ asin_detail.id }}" title="删除">
                        <i class="fa fa-trash-o"></i></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
</div>

</div>
{% endblock %}

{% block extrajsexternal %}
<script type="text/javascript">
$(function() {

    function convert_to_readable_date(date_time_string) {
        var newDate = moment(date_time_string).format('MM/DD/YYYY, h:mm:ss a')
        return newDate
    }

    $('#login_form').on('submit', function(event){
        event.preventDefault();
        console.log("form submitted!")  // sanity check
        create_post();
    });

    $("#item").on('click', 'a[id^=delete-item-]', function(){
        var post_primary_key = $(this).attr('id').split('-')[2];
        console.log(post_primary_key) // sanity check
        delete_post(post_primary_key);
    });

        // AJAX for posting
    function create_post() {
        console.log("create post is working!") // sanity check
        $.ajax({
            url : "api/v1/posts/", // the endpoint
            type : "POST", // http method
            data : { text : $('#id_asins_in').val(), text : $('#id_country').val(), author: $('#user').text()}, // data sent with the post request
            // handle a successful response
            success : function(json) {
                $('#id_asins_in').val(''); // remove the value from the input
                console.log(json); // log the returned json to the console



                $.each(json['Items'], function(key, val) {

                $("#item").prepend("<td>"+val.get_country_display+"</td>
                        <td><img src="+val.img_url+"></td>
                        <td > <a href='"+val.detail_page_url+"' target='_blank'>+val.asin+"</a> </td>
                        <td>"+val.title+"</td>
                        <td>"+val.price+"</td>
                        <td>"+val.bsr_rank+"</td>
                        <td>"+val.brand+"("+val.label+")</td>
                        <td><a id='delete-item-"+val.id+"' href='/asin_detail/delete/"+val.id+"' title='删除'>
                        <i class='fa fa-trash-o'></i></a></td>");
                });

                console.log("success"); // another sanity check
            },
            // handle a non-successful response
            error : function(xhr,errmsg,err) {
                $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
            }
        });
    };

        // AJAX for deleting
    function delete_post(post_primary_key){
        if (confirm('are you sure you want to remove this post?')==true){
            $.ajax({
                url : "api/v1/posts/"+post_primary_key, // the endpoint
                type : "DELETE", // http method
                data : { postpk : post_primary_key }, // data sent with the delete request
                success : function(json) {
                    // hide the post
                  $('#post-'+post_primary_key).hide(); // hide the post on success
                  console.log("post deletion successful");
                },

                error : function(xhr,errmsg,err) {
                    // Show an error
                    $('#results').html("<div class='alert-box alert radius' data-alert>"+
                    "Oops! We have encountered an error. <a href='#' class='close'>&times;</a></div>"); // add error to the dom
                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        } else {
            return false;
        }
    };


});

</script>
{% endblock %}