amazon_crawler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
import debug_toolbar
from django.contrib.auth.views import (
    password_reset_done,
    password_reset_confirm,
    password_reset_complete)


urlpatterns = [
    url(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    url(r'^guwei_administration/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^find_none/', views.find_none, name='find_none'),
    url(r'^converter/', views.converter, name='converter'),
    url(r'^keyword_rank/', include('keyword_rank.urls', namespace='keyword_rank')),
    url(r'^rele_keyword/', include('rele_keyword.urls', namespace='rele_keyword')),
    url(r'^inventory/', include('inventory.urls', namespace='inventory')),
    url(r'^asin_keyword/', include('asin_keyword.urls', namespace='asin_keyword')),
    url(r'^asin_detail/', include('asin_detail.urls', namespace='asin_detail')),
    url(r'^follow_sale/', include('follow_sale.urls', namespace='follow_sale')),
    url(r'^prime_asins/', include('prime_asins.urls', namespace='prime_asins')),
    url(r'^review_monitor/', include('review_monitor.urls', namespace='review_monitor')),
    url(r'^review_qa_collect/', include('review_qa_collect.urls', namespace='review_qa_collect')),
    url(r'^short_url/', include('short_url.urls', namespace='short_url')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^actions/', include('actions.urls', namespace='actions')),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^recharge/', include('payment.urls', namespace='payment')),
    url(r'^upload/', include('upload.urls', namespace='upload')),
    url(r'^core/', include('core.urls', namespace='core')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^(?P<shorten_id>\w{6})$',views.redirect_original, name='redirectoriginal'),
    url(r'^password/reset/done/$',password_reset_done,name='password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^password_reset_complete/$',password_reset_complete,name='password_reset_complete'),
    url(r'^check/', views.check, name='check'),
    # when short URL is requested it redirects to original URL
]

blog/urls.py
from django.conf.urls import url

from .views import BlogDetailView, BlogListView, BlogTagListView


urlpatterns = [
    url(r'^$',BlogListView.as_view(),name='blog_list_view'),
    url(r'^tag/(?P<tag>[\w ]+)/$',BlogTagListView.as_view(),name='blog_tag_list_view'),
    url(r'^(?P<slug>[\w-]+)/$',BlogDetailView.as_view(),name='blog_detail_view'),
]

inventory/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.inventory_submit, name='inventory_submit'),
    url(r'^add_monitor/$', views.add_monitor, name='add_monitor'),
    url(r'^more_monitor/(?P<id>\d+)/$', views.more_monitor, name="more_monitor"),
    url(r'^delete/(?P<id>\d+)/$', views.delete, name="delete"),
]

payment/urls.py
#-*- coding:utf-8 -*-

from django.views.generic import TemplateView
from . import views
from django.conf.urls import url


urlpatterns =[
    url(r'^$', TemplateView.as_view(template_name="crawler/payment/recharge.html"), name='recharge'),
    url(r'^success/$', TemplateView.as_view(template_name="crawler/payment/success.html"), name="payment_success"),
    url(r'^error/$', TemplateView.as_view(template_name="crawler/payment/error.html"), name="payment_error"),
    url(r'^upgrade/(?P<add_credit>\w+)/$', views.upgrade_account, name="upgrade_account"),
    url(r'^return_url/$', views.return_url_handler, name="payment_return_url"),
    url(r'^notify_url/$', views.notify_url_handler, name="payment_notify_url"),
]

inventory/models.py
from django.db import models
from django.utils.text import slugify
from django.core.urlresolvers import reverse
import random
from django.conf import settings


class Inventory(models.Model):
    COUNTRY_CHOICES = (('us', '美国'),('ca', '加拿大'),('fr', '法国'),
                       ('de', '德国'),('it', '意大利'),('jp', '日本'),
                       ('es', '西班牙'),('uk', '英国'),)
    asin = models.CharField(max_length = 100)
    title = models.CharField(max_length = 2000)
    inventory = models.IntegerField(null=True,blank=True,default=0)
    img_url= models.URLField(null=True,max_length=5000)
    detail_page_url = models.URLField(null=True,max_length=5000)
    category = models.CharField(max_length = 1000,null=True,blank=True)
    price_unit = models.CharField(max_length = 100,null=True,blank=True)
    country = models.CharField(max_length=50,choices=COUNTRY_CHOICES,default='us')
    created = models.DateTimeField(blank = True,null = True,auto_now_add=True)
    slug = models.SlugField(max_length = 25,db_index=True,unique=True)
    text = models.CharField(max_length=5000)

    def __str__(self):
        #return self.country,'国家的ASIN',self.asin,'的库存'
        return '%s的商品 %s 的库存' % (self.get_country_display(), self.asin)

    class Meta:
        ordering = ['-created']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.asin+str(random.random())[-3:])
        if not self.text:
            self.text = '%s的商品 %s 的竞品信息' % (self.get_country_display(), self.asin)
        super(Inventory, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('inventory:asin_inventory', args=[self.slug])


class Inventory_time(models.Model):
    asin = models.ForeignKey(Inventory,related_name='inventory_time')
    inventory = models.IntegerField(null=True,blank=True,default=0)
    sale_quan = models.PositiveIntegerField(null=True,blank=True,)
    reviews = models.PositiveIntegerField(default=0)
    reviews_add = models.PositiveIntegerField(default=0)
    bsr_rank = models.PositiveIntegerField(null=True,blank=True)
    star = models.CharField(max_length = 50,blank=True,null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2,null=True)
    sale_amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(blank = True,null = True,auto_now_add=True)

    class Meta:
        ordering = ['-date']


class Inventory_to_user(models.Model):
    inventory = models.ForeignKey(Inventory,related_name='inventory_to_user')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='inventory_to_user')
    created = models.DateTimeField(auto_now_add=True,db_index=True)
    updated = models.DateTimeField(auto_now=True)
    expired = models.DateTimeField()

inventory/forms.py
from django import forms
from .models import Inventory


class Inventory_Form(forms.ModelForm):

    class Meta:
        model = Inventory
        fields = ('asin','country',)

inventory/views.py
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from core.decorators import ajax_required
from django.shortcuts import render, get_object_or_404, redirect
from .forms import Inventory_Form
from .models import Inventory,Inventory_time,Inventory_to_user
from .inventory import inventory_query
from celery.result import AsyncResult
from accounts.models import UserSettings
from actions.utils import create_action
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
import datetime,time
from django.db.models import F
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def inventory_submit(request):
#    print(UserSettings.objects.get(user=request.user).status)
#    if not UserSettings.objects.get(user=request.user).status in ABOVE_V1:
#        messages.success(request, '请购买VIP后继续使用网站功能.')
#        return redirect('/recharge')
    inventory_to_users = Inventory_to_user.objects.filter(user=request.user)
    inventorys = inventory_to_users.values_list('inventory', flat=True)
    inventorys = Inventory.objects.filter(id__in=inventorys)
    inventory = None
    inventory_time = None
    inventory_times = None
    inventory_to_user = False
    form = Inventory_Form(data=request.POST or None)
    if form.is_valid():
        user_setting= UserSettings.objects.filter(user=request.user)
        if user_setting[0].credit < 6:
            return redirect('/payment')
        new_asin = form.save(commit=False)
        if Inventory.objects.filter(asin=new_asin.asin,country=new_asin.country):
            inventory = Inventory.objects.filter(asin=new_asin.asin,country=new_asin.country)[0]
            inventory_times = Inventory_time.objects.filter(asin=inventory)
            inventory_time=Inventory_time.objects.filter(asin=inventory).first()
            if Inventory_to_user.objects.filter(inventory=inventory,user=request.user):
                inventory_to_user = True
        else:
            task = inventory_query.delay(new_asin.asin,new_asin.country)
            start = time.time()
            while AsyncResult(task.task_id).status != 'SUCCESS':
                if AsyncResult(task.task_id).status == 'FAILURE' or (time.time()-start)>40:
                    messages.success(request, '该ASIN不存在,请确认后重新查询.本次查询没有扣除积分.')
                    return redirect('/inventory')
                pass
            if AsyncResult(task.task_id).status == 'SUCCESS':
                #if not Inventory.objects.filter(asin=new_asin.asin,country=new_asin.country)[0].inventory_time.all().exists():
                #    Inventory.objects.filter(asin=new_asin.asin,country=new_asin.country)[0].delete()
                try:
                    inventory = Inventory.objects.filter(asin=new_asin.asin,country=new_asin.country)[0]
                    if inventory.inventory==0:
                        inventory.delete()
                        messages.success(request, '没有获得该ASIN的竞品信息,本次查询没有扣除积分.')
                        return redirect('/inventory')
                    else:
                        inventory_times = Inventory_time.objects.filter(asin=inventory)
                        inventory_time=Inventory_time.objects.filter(asin=inventory).first()
                    if Inventory_to_user.objects.filter(inventory=inventory,user=request.user):
                        inventory_to_user = True
                except:
                    messages.success(request, '没有获得该ASIN的竞品信息,本次查询没有扣除积分.')
                    return redirect('/inventory')
    paginator = Paginator(inventorys, 12)
    page = request.GET.get('page')
    try:
        inventorys_page = paginator.page(page)
    except PageNotAnInteger:
        inventorys_page = paginator.page(1)
    except EmptyPage:
        inventorys_page = paginator.page(paginator.num_pages)
    return render(request, 'crawler/inventory/inventory_submit.html', {'form': form,'inventorys': inventorys_page,
        'inventory_time':inventory_time,'inventory_to_user':inventory_to_user,'inventory': inventory,'inventory_times':inventory_times})


@ajax_required
@login_required
@require_POST
def add_monitor(request):
    inventory_id = request.POST.get('id') #id的用法
    inventory = Inventory.objects.filter(id=inventory_id)[0]
    if inventory and not Inventory_to_user.objects.filter(user=request.user,inventory=inventory):
        try:
            if Inventory_to_user.objects.filter(user=request.user).count()<36:
                inventory_to_user=Inventory_to_user(inventory=inventory,user=request.user,expired=timezone.now() + datetime.timedelta(days=31))
                inventory_to_user.save()
                if create_action(request.user, '跟踪了', inventory):
                    user_setting= UserSettings.objects.filter(user=request.user)
                    user_setting.update(credit=F('credit')-6)
                return JsonResponse({'status':'ok'}) #点击按钮后status是ok
        except:
            pass
    return JsonResponse({'status':'ko'}) #没点击按钮,status是ko


def more_monitor(request, id):
    inventory=get_object_or_404(Inventory, id=id)
    inventory_to_user=Inventory_to_user.objects.filter(inventory=inventory,user=request.user)
    days = (inventory_to_user[0].expired - datetime.datetime.now(timezone.utc)).days
    if days<92:
        if days>=0:
            inventory_to_user.update(expired=timezone.now()+datetime.timedelta(days=days+31))
        else:
            inventory_to_user.update(expired=timezone.now()+datetime.timedelta(days=31))
        messages.success(request, '%s已经续期一个月' % (inventory.text))
        if create_action(request.user, '续期了', inventory):
            user_setting=UserSettings.objects.filter(user=request.user)
            user_setting.update(credit=F('credit')-6)
        return redirect('/inventory/')
    else:
        messages.success(request, '%s的监控时间超过三个月,请不要继续续期' % (inventory.text))
        return redirect('/inventory/')


def delete(request, id):
    inventory=get_object_or_404(Inventory, id=id)
    if Inventory_to_user.objects.filter(inventory=inventory,user=request.user):
        Inventory_to_user.objects.filter(inventory=inventory,user=request.user).delete()
        messages.success(request, '已经删除%s' % (inventory.text))
        return redirect('/inventory/')

inventory/templates/crawler/inventory/asin_inventory.html
{% extends 'base.html' %}
{% block title %} {{ inventory.title|truncatewords:7 }}的库存 | {{ site_name }}{% endblock %}
{% load static %}

{% block extracss %}
{% endblock %}

{% block rootcontainer %}
 <div class="search_description">
     {% if user.is_authenticated %}
        <span>当前剩余积分：<i class="red">{{user.settings.credit}}</i></span>
        <span class="buy">积分不够？<a href="{% url 'payment:recharge' %}" target="_blank">立即购买</a></span>
        <span>每次查询消耗<i class="red">&nbsp;2&nbsp;</i>积分，24小时内查询同一个Asin，只消耗一次积分</span>
    {% else %}
    <span>新用户免费获得100积分,每次查询消耗<i class="red">&nbsp;2&nbsp;</i>积分，24小时内查询同一个Asin，只消耗一次积分</span>
    {% endif %}
</div>
<div class="container">
    <div id="content">
        {% if messages %} <!--messages的用法-->
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }} <!--safe的用法-->
                        <a href="#" class="close">×</a>
                    </li>
                {% endfor %}
                <br><br>
            </ul>
        {% endif %}
    </div>
<div class="row">
       <div class="col-lg-12 ">
            <div class="search_box">
                <form action="." method="post" onsubmit='showLoading();' id="login_form">
                <!--  <label for="id_asin">Asin:</label>  -->
                <input id="id_asin" class="search_input" placeholder="请输入ASIN" maxlength="100" name="asin" type="text" required="">
                    <select  class="search_select" id="id_country" name="country" required="">

                    <option value="us" selected="selected">美国</option>
                    <option value="ca">加拿大</option>
                    <option value="jp">日本</option>
                    <option value="de">德国</option>
                    <option value="it">意大利</option>
                    <option value="es">西班牙</option>
                    <option value="uk">英国</option>
                </select>
                {% csrf_token %}
                <input type="submit" style="width:196px" value="从ASIN获得库存">
            </form>
            </div>
        </div>

        <div class="col-lg-12 ">
        <img src="{% static "images/spin.gif" %}" id="gif" style="display: none; margin: 0 auto; width: 100px; /* visibility: hidden; */">
        </div>
</div>
</div>

<div class="container">
    <div class="col-sm-12">
    <div class="row-sm-12 col-sm-offset-1">
        <br>
        <div style="overflow: auto;">
            <table id="change" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>ASIN</th>
                        <th>商品名称</th>
                        <th>时间</th>
                        <th>库存</th>
                    </tr>
                </thead>
                <tbody>
                    {% for inventory_time in inventory_times %}
                        <tr>
                            <td>{{ inventory.asin }} </td>
                            <td>{{ inventory.title }}</td>
                            <td>{{ inventory_time.date|date:"Y-m-d H:i:s" }}</td>
                            <td>{{ inventory_time.inventory }}</td>

			</tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    </div>
</div>
{% endblock %}

{% block extrajsexternal %}
    <script type="text/javascript">
        $('#login_form').submit(function() {
            $('#gif').css('display', 'block');
        });
    </script>
    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="/static/main.js"></script>
{% endblock %}

inventory/templates/crawler/inventory/inventory_item.html
{% load inventory_tags %}

<div class="user clearfix" style="position: relative;">
        <img class="user-detail" src="{% if inventory.img_url %}{{ inventory.img_url }}{% else %} /static/images/icons/icon.jpg {% endif %}" width=50 style="width:50px; height:50px;">
        <a class="products_title1" href="{{inventory.detail_page_url}}">{{ inventory.title }}</a>
        <a class="products_title" href="javascript:;" id="{{inventory.id}}"  onclick="amz668.viewInventory(this.id);return false;"><i class="fa fa-bar-chart" aria-hidden="true"></i> 竞品信息</a>


    <span class="products_id">{{inventory.get_country_display}}:{{inventory.asin}}</span>
    {% latest_inven inventory as latest_inven %}
    <span class="in_stock" >最新库存:{% ifequal latest_inven 999 %}999+{% else %}{{ latest_inven }}{% endifequal %}</span>

    {% days_remain inventory request.user as days %}
    <span class="day_num">剩余天数:{{ days }} </span>
    <a href="/inventory/more_monitor/{{ inventory.id }}" class="renewal_btn" onclick="">续期</a>
   <!--  <a href="javascript:;" class="refresh_btn" onclick="amz668.refreshInventory(this)">刷新</a> -->
    <a href="/inventory/delete/{{ inventory.id }}" class="del_btn"  data="{{ inventory.asin }}" onclick="">删除</a>



    <div id="id_{{inventory.id}}" style="display: none">
    <table id="change" class="display dataTable no-footer" cellspacing="0" role="grid" aria-describedby="change_info" style="width: 100%;">
        <thead>
            <tr role="row">
                <th class="sorting" tabindex="0" aria-controls="change" rowspan="1" colspan="1" aria-label="日期: activate to sort column ascending" style="width: 50px;">日期</th>
                <th class="sorting" tabindex="0" aria-controls="change" rowspan="1" colspan="1" aria-label="库存: activate to sort column ascending" style="width: 20px;">库存</th>
                <th class="sorting" tabindex="0" aria-controls="change" rowspan="1" colspan="1" aria-label="参考销量: activate to sort column ascending" style="width: 20px;">参考销量</th>
                <th class="sorting" tabindex="0" aria-controls="change" rowspan="1" colspan="1" aria-label="价格: activate to sort column ascending" style="width: 20px;">价格({{ inventory.price_unit }})</th>
                <th class="sorting" tabindex="0" aria-controls="change" rowspan="1" colspan="1" aria-label="销售金额: activate to sort column ascending" style="width: 40px;">销售金额({{ inventory.price_unit }})</th>
                <th class="sorting" tabindex="0" aria-controls="change" rowspan="1" colspan="1" aria-label="评论: activate to sort column ascending" style="width: 50px;">评论数</th>
                <th class="sorting" tabindex="0" aria-controls="change" rowspan="1" colspan="1" aria-label="评论: activate to sort column ascending" style="width: 50px;">评论星级</th>
                <th class="sorting" tabindex="0" aria-controls="change" rowspan="1" colspan="1" aria-label="BSR排名: activate to sort column ascending" style="width: 50px;">BSR排名</th>
            </tr>
        </thead>
        <tbody id="result">
            {% inven_time inventory as in_times %}
            {%for in_time in in_times%}
            <tr role="row" class="odd">
                <td>{{ in_time.date|date:"m月d日"}}</td>
                <td>{% ifequal in_time.inventory 999 %}999+{% else %}{{ in_time.inventory }}{% endifequal %}</td>
                <td>{{ in_time.sale_quan }}</td>
                <td>{{ in_time.price }}</td>
                <td>{{ in_time.sale_amount }}</td>
                <td>{{ in_time.reviews }}{% if in_time.reviews_add > 0 %}(⬆{{ in_time.reviews_add }}){% endif %}</td>
                <td>{% if in_time.star %}{{ in_time.star }}{% else %}没有开始跟踪{% endif %}</td>
                <td>{% if in_time.bsr_rank %}{{ in_time.bsr_rank }} {% else %} 暂无排名 {% endif %}</td>
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>

inventory/templates/crawler/inventory/inventory_submit.html
{% extends 'base.html' %}
{% block title %} 从商品ASIN获得竞品信息 | {{ site_name }}{% endblock %}
{% load static %}
{% load inventory_tags %}
{% block extracss %}
{% endblock %}
{% block rootcontainer %}
    <div class="search_description">
     {% if user.is_authenticated %}
        <span>当前剩余积分：<i class="red">{{user.settings.credit}}</i></span>
        <span class="buy">积分不够？<a href="{% url 'payment:recharge' %}" target="_blank">立即购买</a></span>
    <span>免费查询竞品信息,每跟踪一个月消耗<i class="red">&nbsp;6&nbsp;</i>积分</span>
    {% else %}
    <span>新用户免费获得100积分,免费查询竞品信息,每跟踪一个月消耗<i class="red">&nbsp;6&nbsp;</i>积分</span>
    {% endif %}
        <span class="buy"><a href="/blog/whatissuperurl/"><i class="fa fa-lightbulb-o" aria-hidden="true"></i>&nbsp;帮助中心</a></span>
    </div>
<div class="container">
    <div id="content">
        {% if messages %} <!--messages的用法-->
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">
                        {{ message|safe }} <!--safe的用法-->
                        <a href="#" class="close">×</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
<div class="row">
        <div class="col-lg-12 ">
            <div class="search_box">
                <form action="." method="post" id="login_form">
                <!--  <label for="id_asin">Asin:</label>  -->
                <input id="id_asin" class="search_input" placeholder="请输入ASIN" maxlength="100" name="asin" type="text" required="">
                    <select  class="search_select" id="id_country" name="country" required="">
                    <option value="us" selected="selected">美国</option>
                    <option value="ca">加拿大</option>
                    <option value="jp">日本</option>
                    <option value="fr">法国</option>
                    <option value="uk">英国</option>
                    <option value="de">德国</option>
                    <option value="it">意大利</option>
                    <option value="es">西班牙</option>
                </select>
                {% csrf_token %}
                <input type="submit" style="width:196px" value="获得竞品信息" onclick="get();">
            </form>
            </div>
            <p style="text-align: center;margin-top: -20px;">（PS：获得竞品信息后，可对商品进行持续跟踪）</p>
        </div>
        <div class="col-lg-12 ">
        <img src="{% static "images/spin.gif" %}" id="gif" style="display: none; margin: 0 auto; width: 100px; /* visibility: hidden; */">
        </div>
</div>
    <div class="row-sm-12 col-sm-offset-1">
    {% if inventory %}
        <div style="overflow: auto;">
            <table id="change" class="display" cellspacing="0" width="90%">
                <thead>
                    <tr>
                        <th width="20%">ASIN</th>
                        <th width="28%">商品名称</th>
                        <th width="7%">库存</th>
                        <th width="11%">bsr排名</th>
                        <th width="9%">价格{{ inventory_time.price_unit }}</th>
                        <th width="10%">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td align="center"><img src="{{ inventory.img_url }}" width=70 > &emsp;{{ inventory.asin }} </td>
                        <td align="center">{{ inventory.title }}</td>
                        <td align="center">{% ifequal inventory.inventory  999 %}999+{% else %}{{ inventory.inventory }}{% endifequal %}</td>
                        <td align="center">{{ inventory_time.bsr_rank }}</td>
                        <td align="center">{{ inventory_time.price }}</td>
                        <td align="center">
                            {% if not inventory_to_user %}
                                <a href="javascript:;" data-id="{{ inventory.id }}" data-action="add_monitor"  class="add_monitor add_btn" onclick="javascript:layer.msg('添加成功！', {icon: 1});">添加到跟踪竞品 </a>
                            {% else %}
                                 <span>正在跟踪竞品信息</span>
                            {% endif %}
                        </td>
                     </tr>
                </tbody>
            </table>
        </div>
    {% endif %}
    </div>
        <ul class="messages"><li class="success">正在跟踪竞品信息的商品(每天凌晨3:00更新信息)</li></ul>
    {% if inventorys %}{% include "crawler/action/pagination.html" with page=inventorys %}{% endif %}
        <div id="people-list">
            {% for inventory in inventorys %}
                {% include "crawler/inventory/inventory_item.html" with inventory=inventory %}
            {% endfor %}
        </div>
</div>
{% endblock %}
{% block extrajsexternal %}
<script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
<script>
     var csrftoken = $.cookie('csrftoken');
     function csrfSafeMethod(method) {
       // these HTTP methods do not require CSRF protection
       return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
     }
     $.ajaxSetup({
       beforeSend: function(xhr, settings) {
         if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
           xhr.setRequestHeader("X-CSRFToken", csrftoken);
} }
});
$(document).ready(function(){
$('a.add_monitor').click(function(e){
    e.preventDefault();
    $.post('{% url "inventory:add_monitor" %}',
        {
            id: $(this).data('id')
        },
        function(data){
            if (data['status'] == 'ok')
            {
                // toggle link text
                $('a.add_monitor').text('已经开始跟踪竞品信息');
                $('a.add_monitor').removeClass('add_monitor');
                location.reload();
            }
            if (data['status'] == 'ko')
            {
                // toggle link text
                $('a.add_monitor').text('因为网站资源有限,允许最多跟踪36条竞品信息.您跟踪的竞品信息已经达到36条.');
                $('a.add_monitor').removeClass('add_monitor');
            }
    });
});
     });
</script>
<script type="text/javascript">
$('#login_form').submit(function() {
    $('#gif').css('display', 'block');
});
</script>
{% endblock %}